kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: redis
  commands:
  - echo hello 
  - echo hello > /tmp/world.txt
  - sleep 5
  - redis-cli -h cache ping

- name: check
  image: alpine
  commands:
  - echo hello 
  - cat /tmp/world.txt

services:
  - name: hello-world
    image: hello-world
  - name: redis
    image: redis